# Generated by Django 4.2.1 on 2023-07-17 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agents',
            name='id',
        ),
        migrations.AlterField(
            model_name='agents',
            name='agent_code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_name', models.CharField(max_length=100)),
                ('cust_code', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('cust_mobile', models.CharField(max_length=100)),
                ('agent_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.agents')),
            ],
        ),
    ]
