# Generated by Django 4.2.1 on 2023-07-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_agents_id_alter_agents_agent_code_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='agent_code',
            new_name='agent_name',
        ),
    ]
